name: workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Node setup  
      uses: actions/setuo-node@v4.0.3
      with:
        node-version: '18.x'

    - run: make setup
    - run: make test
    - run: make lint

    - name: Print Hello from Hexlet
      uses: hexlet-components/hello-from-hexlet-action@release
